# Generated by Django 4.1.5 on 2023-01-13 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_todomodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='time',
            new_name='do_time',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='date',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
