# Generated by Django 4.1.5 on 2023-01-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_rename_time_todomodel_do_time_remove_todomodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='do_time',
            field=models.TimeField(),
        ),
    ]
