# Generated by Django 4.1.5 on 2023-01-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_todomodel_do_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='do_time',
        ),
    ]
